ParkDistrict.MVC/Models/ApiHelper.cs
using System;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;

namespace ParkDistrict.Models
{
    class ApiHelper
    {
        public static async Task<string> ApiCallIndex()
        {
            RestClient client = new RestClient("http://localhost:5000/api/parks");
            RestRequest request = new RestRequest(Method.GET);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallIndexSearch(string search)
        {
            RestClient client = new RestClient("http://localhost:5000/api/parks");
            RestRequest request = new RestRequest(Method.GET);
            request.AddParameter("flex", search);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallDetails(int id)
        {
            RestClient client = new RestClient("http://localhost:5000");
            RestRequest request = new RestRequest("/api/parks/{id}", Method.GET);
            request.AddUrlSegment("id", id);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallCreate(Park park)
        {
            RestClient client = new RestClient("http://localhost:5000");
            RestRequest request = new RestRequest("api/parks", Method.POST);
            request.AddJsonBody(park);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallDelete(int id)
        {
            RestClient client = new RestClient("http://localhost:5000");
            RestRequest request = new RestRequest("api/parks/{id}", Method.DELETE);
            request.AddUrlSegment("id", id);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallEdit(Park park)
        {
            RestClient client = new RestClient("http://localhost:5000");
            RestRequest request = new RestRequest("api/parks/{id}", Method.PUT);
            request.AddUrlSegment("id", park.ParkId);
            request.AddJsonBody(park);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }
    }
}

ParkDistrict.MVC/Models/Park.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
namespace ParkDistrict.Models
{
    public class Park
    {
        public int ParkId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public bool Playground { get; set; }
        public bool PicnicArea { get; set; }
        public bool Bathroom { get; set; }

        public static List<Park> ParkListSearch(string search)
        {
            List<Park> park;
            if (string.IsNullOrEmpty(search))
            {
                var apiCallTask = ApiHelper.ApiCallIndex();
                var result = apiCallTask.Result;

                JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
                park = JsonConvert.DeserializeObject<List<Park>>(jsonResponse.ToString());
            }
            else
            {
                var apiCallTask = ApiHelper.ApiCallIndexSearch(search);
                var result = apiCallTask.Result;

                JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
                park = JsonConvert.DeserializeObject<List<Park>>(jsonResponse.ToString());
            }
            return park;
        }

        public static Park ParkDetails(int id)
        {
            var apiCallTask = ApiHelper.ApiCallDetails(id);
            var result = apiCallTask.Result;
            JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
            Park mushroom = JsonConvert.DeserializeObject<Park>(jsonResponse.ToString());
            Console.WriteLine(mushroom);
            return mushroom;
        }

        public async Task<int> ParkCreate()
        {
            var result = await ApiHelper.ApiCallCreate(this);
            return 0;
        }

        public async static Task<int> ParkDelete(int id)
        {
            Console.WriteLine($"mushroom delete id = {id}");
            var result = await ApiHelper.ApiCallDelete(id);
            return 0;
        }

        public async static Task<int> ParkEdit(Park mushroom)
        {
            var result = await ApiHelper.ApiCallEdit(mushroom);
            return 0;
        }

    }
}

ParkDistrict.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ParkDistrict.Models;

namespace ParkDistrict.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

ParkDistrict.MVC/Controllers/ParksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ParkDistrict.Models;

namespace ParkDistrict.Controllers
{
    public class ParksController : Controller
    {
        public IActionResult Index(string search)
        {
            var parkList = Park.ParkListSearch(search);
            return View(parkList);
        }

        [HttpGet("Parks/{id}")]
        public ActionResult Details(int id)
        {
            Park thisPark = Park.ParkDetails(id);
            return View(thisPark);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Park park)
        {
            await park.ParkCreate();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id, string name)
        {
            var park = Park.ParkDetails(id);
            return View(park);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {
            await Park.ParkDelete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var park = Park.ParkDetails(id);
            return View(park);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Park park)
        {
            await Park.ParkEdit(park);
            return RedirectToAction("Index");
        }
    }
}

ParkDistrict.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="splashHeader">
    <h1>Portland's Parks</h1>

</div>

ParkDistrict.MVC/Views/Parks/Create.cshtml
@using ParkDistrict.Models;
@model Park;


<h2>Create a new park</h2>

@using (Html.BeginForm())
{
    <label for="Name">Park Name:</label>
    @Html.TextBoxFor(model => model.Name)
    <br>

    <label for="Name">Park Location:</label>
    @Html.TextBoxFor(model => model.Location)
    <br>

    <label for="Name">Playground:</label>
    @Html.CheckBoxFor(m => m.Playground)
    <br>
    

    <label for="Name">Picnic Area:</label>
    @Html.CheckBoxFor(model => model.PicnicArea)
    <br>

    <label for="Name">Public Bathroom:</label>
    @Html.CheckBoxFor(model => model.Bathroom)
    <br>


    <input type="submit" value="Add new park" class="btn btn-primary" />
}

ParkDistrict.MVC/Views/Parks/Delete.cshtml
@using ParkDistrict.Models;
@model ParkDistrict.Models.Park;

<h1>Delete</h1>

<h2>Are you sure you want to delete @Model.Name?</h2>

@using (Html.BeginForm())
{
    <input type="hidden" id="ParkId" name="id" value="@Model.ParkId"/>
    
    <input type="submit" value="Remove" />
}
@Html.ActionLink("Back to List", "Index")

ParkDistrict.MVC/Views/Parks/Details.cshtml
@using ParkDistrict.Models;
@model ParkDistrict.Models.Park;
<h2>@Model.Name Details</h2>
<p>Location: @Model.Location</p>
@if (@Model.Playground == true)
{
    <p>Playground: Yes</p>
}
else
{
    <p>Playground: No</p>
}
@if (@Model.PicnicArea == true)
{
    <p>Picnic Area: Yes</p>
}
else
{
    <p>Picnic Area : No</p>
}
@if (@Model.Bathroom == true)
{
    <p>Public Bathroom: Yes</p>
}
else
{
    <p>Public Bathroom: No</p>
}
<hr>
<a href='@Url.Action("Edit", new {id = @Model.ParkId})'>
    <img class="createImg", src='@Url.Content("~/img/edit.png")' />
</a>

<a href='@Url.Action("Delete", new {id = @Model.ParkId})'>
    <img class="deleteImg", src='@Url.Content("~/img/delete.png")' />
</a>

ParkDistrict.MVC/Views/Parks/Edit.cshtml
@using ParkDistrict.Models;
@model ParkDistrict.Models.Park;
<h1>Edit</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ParkId)

    <label for="Name">Park Name:</label>
    @Html.TextBoxFor(model => model.Name)
    <br>

    <label for="Name">Park Location:</label>
    @Html.TextBoxFor(model => model.Location,new { style = "width: 400px;" })
    <br>

    <label for="Name">Playground:</label>
    @Html.CheckBoxFor(m => m.Playground)
    <br>
    

    <label for="Name">Picnic Area:</label>
    @Html.CheckBoxFor(model => model.PicnicArea)
    <br>

    <label for="Name">Public Bathroom:</label>
    @Html.CheckBoxFor(model => model.Bathroom)
    <br>

    <input type="submit" value="Save Changes" class="btn btn-primary" />
}

ParkDistrict.MVC/Views/Parks/Index.cshtml
@using ParkDistrict.Models;

@foreach (Park park in Model)
{
    <p>@Html.ActionLink($"{@park.Name}", "Details", "Parks", new {id = park.ParkId})</p>
}
<br>

<a href='@Url.Action("Create", "Parks")'>
    <img class="createImg", src='@Url.Content("~/img/add.jpg")' />
</a>

ParkDistrict.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang='en'>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Park District"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-fallback-test-class="sr-only"
            asp-fallback-test-property="position" asp-fallback-test-value="absolute" crossorigin="anonymous"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" href="\">Park District</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex flex-lg-row">
                    <ul class="navbar-nav flex-grow-1 mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Index" href="\Parks"><img class="parkImg" src="~/img/park.png" alt="Park">Parks</a>
                            
                        </li>


                    </ul>

                    <form class="form-inline my-2 my-lg-0" method="get" action="/">
                        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-lg btn-outline-primary my-2 my-sm-0" formaction="/Parks"
                            type="submit"><img class="searchImg" src="~/img/search.png" alt="Magnifying glass"></button>
                    </form>
                    
                    <div id="login">
                        <ul class="navbar-nav flex-grow-1 mr-auto">
                            <li class="nav-item">
                              
                                <!-- <a class="nav-link text-dark" asp-area="" asp-controller="Index"
                                    href="\Account">Logout</a>
                       
                                <a class="nav-link text-dark" asp-area="" asp-controller="Index"
                                    href="\Account">Login/Register</a> -->
                                
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <footer class="border-top bg-white footer text-muted">
            <div class="container">
                &copy; 2019 - Park District - <a asp-area="" asp-controller="Home"
                    asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js" asp-fallback-test="window.jQuery" crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>